AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: modify-resource
    Description: Updates resources in DynamoDB
    Author: Unit
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/BIBSYSDEV/data-persistence
    SourceCodeUrl: https://github.com/BIBSYSDEV/data-persistence

Parameters:
  ResourceTable:
    Type: String
    Description: Reference to table containing resource data

Resources:
  ModifyResource:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./modify_resource
      Handler: app.handler
      Runtime: python3.7
      Events:
        PutEvent:
          Type: Api
          Properties:
            Path: /{id}
            Method: PUT
