AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: modify-resource
    Description: Updates resources in DynamoDB
    Author: Unit
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/BIBSYSDEV/modify-resource
    SourceCodeUrl: https://github.com/BIBSYSDEV/modify-resource

Parameters:
  ResourceTable:
    Type: String
    Description: Reference to table containing resource data
  CognitoAuthorizerArn:
    Type: String
    Description: Reference to Cognito UserPool for the stage


Resources:

  ModifyResourceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref CognitoAuthorizerArn


  ModifyResource:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./modify_resource
      Handler: app.handler
      Runtime: python3.7
      Events:
        PutEvent:
          Type: Api
          Properties:
            Path: /{id}
            Method: PUT
            RestApiId: !Ref ModifyResourceApi
      Environment:
        Variables:
          TABLE_NAME: !Ref ResourceTable
          REGION: !Ref AWS::Region

Outputs:
  FetchResourceApiName:
    Value: !Ref ModifyResourceApi
    Export:
      Name: !Sub "${AWS::StackName}-Api"

