AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: modify-resource
    Description: Updates resources in DynamoDB
    Author: Unit
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/BIBSYSDEV/modify-resource
    SourceCodeUrl: https://github.com/BIBSYSDEV/modify-resource

Parameters:
  ResourceTable:
    Type: String
    Description: Reference to table containing resource data
  CognitoAuthorizerArn:
    Type: String
    Description: Reference to Cognito UserPool for the stage
  CustomDomain:
    Type: String
    Description: Custom API to connect this lambda to
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain


Resources:

  ModifyResourceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref CognitoAuthorizerArn
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'OPTIONS,PUT'"

  ModifyResource:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./modify_resource
      Handler: app.handler
      Runtime: python3.7
      Events:
        PutEvent:
          Type: Api
          Properties:
            Auth:
              Authorizer: MyCognitoAuthorizer
            Path: /{id}
            Method: PUT
            RestApiId: !Ref ModifyResourceApi
      Environment:
        Variables:
          TABLE_NAME: !Ref ResourceTable
          REGION: !Ref AWS::Region
          ALLOWED_ORIGIN: '*'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ResourceTable

  ModifyResourceBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref CustomDomain
      RestApiId: !Ref ModifyResourceApi
      Stage: !Ref ModifyResourceApi.Stage
